### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by DavidJBall** [Niryo/controllerim#10]
This library looks great but we have a requirement that we must write everything in typescript. Do you have any plans to add the typings for this project?

**Comment by Niryo** [comment]
Hi, I definitely want to migrate the code to typescript. I am also planning to support react hooks and move the need for initiallizing the controllers in the deprecated componentWillMount method.

But currently I don't have time for this. I have my own project that use controllerim (in react native) so most of the work I am putting into controllerim is for solving immediate issues I have, but currently it's pretty stable for me right now, so I barely touch it.

I am guessing that I will have to touch it again soon, when componentWillMount will be deprecated for good, and then i'll probably do a big re-write with all the typescript changes and hooks and everything (btw, it wan't take too much time, probably couple of weekends). But I can't give you an ETA for it.

**Comment by Niryo** [comment]
Controllerim v3 supports typescript
