### ISSUE TITLE
Using controllerim with functional react components?

### ISSUE THREAD

**Issue by joshglenn** [Niryo/controllerim#11]
Is there a way to use controllerim with functional react components?

**Comment by Niryo** [comment]
currently no, because controllerim was build before hooks and passing the context to function component was a bit of a problem. But I am going to support hooks soon. I am not sure yet how it is going to look, but it will probably be big change and a major version update of the library.

**Comment by joshglenn** [comment]
Ok. I've been using it with class-based components. So far, so good. I find controllerim is way easier to work with than redux.

**Comment by Niryo** [comment]
Thanks for the feedback. Migrating controllerim to support hooks is on top of my mind, hope it will happen soon. It will also remove the need for using componentWillMount so it's very important.

**Comment by Niryo** [comment]
@joshglenn I have released a new version of Controllerim. The new version supports functional react components. Currently you need to wrap you react components with observer, but I will consider adding a hook the will eliminate the need for observer

**Comment by joshglenn** [comment]
Fantastic. Thank you. I'll let you know how things go.
