### ISSUE TITLE
Port controllerim to Flutter

### ISSUE THREAD

**Issue by diufanman** [Niryo/controllerim#6]
Would you consider to port controllerim to Flutter?

**Comment by Niryo** [comment]
I never worked with Flutter and I don't know anything about it's architecture. 
I somehow took the idea for Controllerim  from Angular, so I would guess that Flutter, being another google product, already has some kind of the same concept?

**Comment by Niryo** [comment]
Ok, so I guess that some day i'll need to learn Flutter to grasp the idea and concepts behind it:)
tnx for your feedback!
